@Host = http://localhost:5204

GET {{Host}}/auth/login
Accept: application/json;v=0.1

{
    "email": "grigoriy21@yandex.ru",
    "password": "gwertyxyz"
}

###

POST {{Host}}/auth/signup
Accept: application/json;v=0.1

{
    "identityName": "grigory",
    "email": "grigoriy21@yandex.ru",
    "password": "gwertyxyz"
}

###
