services:
  razdor-app:
    build: .
    command: /app/Razdor.StartApp.dll
    environment:
      - ConnectionStrings:messagesdb=mongodb://admin:admin@localhost:27017/messagesdb?authSource=admin&authMechanism=SCRAM-SHA-256
      - ConnectionStrings:communitydb=mongodb://admin:admin@localhost:27017/communitydb?authSource=admin&authMechanism=SCRAM-SHA-256
      - ConnectionStrings:identitydb=Host=localhost;port=5432;database=identitydb;username=admin;password=admin
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - local_storage:/api
    depends_on:
      - mongodb
      - postgres
      - razdor-migrations
  
  razdor-migrations:
    build: .
    command: /identity-migrations/Razdor.Identity.MigrationService.dll
    environment:
      - ConnectionStrings:identitydb=Host=localhost;port=5432;database=identitydb;username=admin;password=admin
    network_mode: host
    depends_on:
      - postgres
  
  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    network_mode: host
  
  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=identitydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

volumes:
  local_storage:
  postgres_data:
  mongo_data: