// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Shared.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Identity.Infrastructure.DataAccess
{
    public static class BaseSnowflakeEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref ulong Id(BaseSnowflakeEntity @this);
    }
}
