// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Identity.Domain.Users;
using Razdor.Shared.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Identity.Infrastructure.DataAccess
{
    public static class UserAccountUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CredentialsChangeDate>k__BackingField")]
        public static extern ref DateTimeOffset CredentialsChangeDate(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Email>k__BackingField")]
        public static extern ref string Email(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HashedPassword>k__BackingField")]
        public static extern ref string HashedPassword(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IdentityName>k__BackingField")]
        public static extern ref string IdentityName(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_isOnline")]
        public static extern ref bool _isOnline(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_nickname")]
        public static extern ref string _nickname(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RegistrationDate>k__BackingField")]
        public static extern ref DateTimeOffset RegistrationDate(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_selectedStatus")]
        public static extern ref SelectedCommunicationStatus _selectedStatus(UserAccount @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_avatar")]
        public static extern ref MediaFileMeta _avatar(UserAccount @this);
    }
}
