// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Messages.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class AttachmentUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FileName>k__BackingField")]
        public static extern ref string FileName(Attachment @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref ulong Id(Attachment @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MediaType>k__BackingField")]
        public static extern ref string MediaType(Attachment @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref long Size(Attachment @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceUrl>k__BackingField")]
        public static extern ref string SourceUrl(Attachment @this);
    }
}
