// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Messages.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class AttachmentMetaUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref ulong Id(AttachmentMeta @this);
    }
}
