// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Shared.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class MediaFileMetaUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FileName>k__BackingField")]
        public static extern ref string FileName(MediaFileMeta @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MediaType>k__BackingField")]
        public static extern ref string MediaType(MediaFileMeta @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref long Size(MediaFileMeta @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceUrl>k__BackingField")]
        public static extern ref string SourceUrl(MediaFileMeta @this);
    }
}
