// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using MongoDB.EntityFrameworkCore.Storage;
using Razdor.Messages.Domain.Mentioning;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    [EntityFrameworkInternal]
    public partial class MentionedUserEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Razdor.Messages.Domain.Mentioning.Mentions._users#MentionedUser",
                typeof(MentionedUser),
                baseEntityType,
                sharedClrType: true,
                propertyCount: 3,
                foreignKeyCount: 1,
                keyCount: 1);

            var mentionsId = runtimeEntityType.AddProperty(
                "MentionsId",
                typeof(ulong),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0ul);
            mentionsId.SetAccessors(
                ulong (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<ulong>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<ulong>(0) == 0UL ? entry.ReadTemporaryValue<ulong>(0) : entry.ReadShadowValue<ulong>(0))),
                ulong (InternalEntityEntry entry) => entry.ReadShadowValue<ulong>(0),
                ulong (InternalEntityEntry entry) => entry.ReadOriginalValue<ulong>(mentionsId, 0),
                ulong (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<ulong>(mentionsId, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            mentionsId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            mentionsId.TypeMapping = MongoTypeMapping.Default.Clone(
                comparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                keyComparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                providerValueComparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                clrType: typeof(ulong));
            mentionsId.SetCurrentValueComparer(new EntryCurrentValueComparer<ulong>(mentionsId));

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetAccessors(
                int (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && entry.ReadShadowValue<int>(1) == 0 ? entry.ReadTemporaryValue<int>(1) : entry.ReadShadowValue<int>(1))),
                int (InternalEntityEntry entry) => entry.ReadShadowValue<int>(1),
                int (InternalEntityEntry entry) => entry.ReadOriginalValue<int>(id, 1),
                int (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<int>(id, 1),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            id.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            id.TypeMapping = MongoTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                clrType: typeof(int));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(ulong),
                propertyInfo: typeof(MentionedUser).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MentionedUser).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0ul);
            userId.SetGetter(
                ulong (MentionedUser entity) => MentionedUserUnsafeAccessors.UserId(entity),
                bool (MentionedUser entity) => MentionedUserUnsafeAccessors.UserId(entity) == 0UL,
                ulong (MentionedUser instance) => MentionedUserUnsafeAccessors.UserId(instance),
                bool (MentionedUser instance) => MentionedUserUnsafeAccessors.UserId(instance) == 0UL);
            userId.SetSetter(
                (MentionedUser entity, ulong value) => MentionedUserUnsafeAccessors.UserId(entity) = value);
            userId.SetMaterializationSetter(
                (MentionedUser entity, ulong value) => MentionedUserUnsafeAccessors.UserId(entity) = value);
            userId.SetAccessors(
                ulong (InternalEntityEntry entry) => MentionedUserUnsafeAccessors.UserId(((MentionedUser)(entry.Entity))),
                ulong (InternalEntityEntry entry) => MentionedUserUnsafeAccessors.UserId(((MentionedUser)(entry.Entity))),
                ulong (InternalEntityEntry entry) => entry.ReadOriginalValue<ulong>(userId, 2),
                ulong (InternalEntityEntry entry) => entry.GetCurrentValue<ulong>(userId),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            userId.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            userId.TypeMapping = MongoTypeMapping.Default.Clone(
                comparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                keyComparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                providerValueComparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                clrType: typeof(ulong));

            var key = runtimeEntityType.AddKey(
                new[] { mentionsId, id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MentionsId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var _users = principalEntityType.AddNavigation("_users",
                runtimeForeignKey,
                onDependent: false,
                typeof(IReadOnlyCollection<MentionedUser>),
                fieldInfo: typeof(Mentions).GetField("_users", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            _users.SetGetter(
                IReadOnlyCollection<MentionedUser> (Mentions entity) => MentionsUnsafeAccessors._users(entity),
                bool (Mentions entity) => MentionsUnsafeAccessors._users(entity) == null,
                IReadOnlyCollection<MentionedUser> (Mentions instance) => MentionsUnsafeAccessors._users(instance),
                bool (Mentions instance) => MentionsUnsafeAccessors._users(instance) == null);
            _users.SetSetter(
                (Mentions entity, IReadOnlyCollection<MentionedUser> value) => MentionsUnsafeAccessors._users(entity) = value);
            _users.SetMaterializationSetter(
                (Mentions entity, IReadOnlyCollection<MentionedUser> value) => MentionsUnsafeAccessors._users(entity) = value);
            _users.SetAccessors(
                IReadOnlyCollection<MentionedUser> (InternalEntityEntry entry) => MentionsUnsafeAccessors._users(((Mentions)(entry.Entity))),
                IReadOnlyCollection<MentionedUser> (InternalEntityEntry entry) => MentionsUnsafeAccessors._users(((Mentions)(entry.Entity))),
                null,
                IReadOnlyCollection<MentionedUser> (InternalEntityEntry entry) => entry.GetCurrentValue<IReadOnlyCollection<MentionedUser>>(_users),
                null);
            _users.SetPropertyIndexes(
                index: 2,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 3,
                storeGenerationIndex: -1);
            _users.SetCollectionAccessor<Mentions, IReadOnlyCollection<MentionedUser>, MentionedUser>(
                IReadOnlyCollection<MentionedUser> (Mentions entity) => MentionsUnsafeAccessors._users(entity),
                (Mentions entity, IReadOnlyCollection<MentionedUser> collection) => MentionsUnsafeAccessors._users(entity) = ((IReadOnlyCollection<MentionedUser>)(collection)),
                (Mentions entity, IReadOnlyCollection<MentionedUser> collection) => MentionsUnsafeAccessors._users(entity) = ((IReadOnlyCollection<MentionedUser>)(collection)),
                IReadOnlyCollection<MentionedUser> (Mentions entity, Action<Mentions, IReadOnlyCollection<MentionedUser>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<Mentions, IReadOnlyCollection<MentionedUser>, MentionedUser>(entity, setter),
                IReadOnlyCollection<MentionedUser> () => ((IReadOnlyCollection<MentionedUser>)(((ICollection<MentionedUser>)(new HashSet<MentionedUser>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var mentionsId = runtimeEntityType.FindProperty("MentionsId");
            var id = runtimeEntityType.FindProperty("Id");
            var userId = runtimeEntityType.FindProperty("UserId");
            var key = runtimeEntityType.FindKey(new[] { mentionsId, id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((MentionedUser)(source.Entity));
                    return ((ISnapshot)(new Snapshot<ulong, int, ulong>(((ValueComparer<ulong>)(((IProperty)mentionsId).GetValueComparer())).Snapshot(source.GetCurrentValue<ulong>(mentionsId)), ((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<ulong>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<ulong>(userId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<ulong, int>(((ValueComparer<ulong>)(((IProperty)mentionsId).GetValueComparer())).Snapshot(default(ulong)), ((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<ulong, int>(default(ulong), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<ulong, int>((source.ContainsKey("MentionsId") ? ((ulong)(source["MentionsId"])) : 0UL), (source.ContainsKey("Id") ? ((int)(source["Id"])) : 0)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<ulong, int>(default(ulong), default(int)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((MentionedUser)(source.Entity));
                    return ((ISnapshot)(new Snapshot<ulong, int>(((ValueComparer<ulong>)(((IProperty)mentionsId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<ulong>(mentionsId)), ((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 3,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 3,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2);
            runtimeEntityType.AddAnnotation("Mongo:ElementName", "Users");

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
