// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Messages.Domain.Mentioning;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class MentionedUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref ulong UserId(MentionedUser @this);
    }
}
