// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Messages.Domain;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class MessageReferenceUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref ulong ChannelId(MessageReference @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MessageId>k__BackingField")]
        public static extern ref ulong MessageId(MessageReference @this);
    }
}
