// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Razdor.Messages.Infrastructure.DataAccess;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MessagesMongoDbContext), typeof(MessagesMongoDbContextModel))]
