// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Razdor.Messages.Domain;
using Razdor.Messages.Domain.Mentioning;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Messages.Infrastructure.DataAccess
{
    public static class MessageUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref ulong ChannelId(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EditedAt>k__BackingField")]
        public static extern ref DateTimeOffset? EditedAt(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsPinned>k__BackingField")]
        public static extern ref bool IsPinned(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Text>k__BackingField")]
        public static extern ref string Text(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref ulong UserId(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Embed>k__BackingField")]
        public static extern ref Embed Embed(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Mentions>k__BackingField")]
        public static extern ref Mentions Mentions(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Reference>k__BackingField")]
        public static extern ref MessageReference Reference(Message @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_attachments")]
        public static extern ref List<Attachment> _attachments(Message @this);
    }
}
