// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain;
using Razdor.Communities.Domain.Members;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class CommunityMemberUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CommunityId>k__BackingField")]
        public static extern ref ulong CommunityId(CommunityMember @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref ulong UserId(CommunityMember @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<JoiningDate>k__BackingField")]
        public static extern ref DateTimeOffset JoiningDate(CommunityMember @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NotificationPolicy>k__BackingField")]
        public static extern ref CommunityNotificationPolicy? NotificationPolicy(CommunityMember @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_roleIds")]
        public static extern ref List<ulong> _roleIds(CommunityMember @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<VoiceState>k__BackingField")]
        public static extern ref VoiceState VoiceState(CommunityMember @this);
    }
}
