// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Razdor.Communities.Infrastructure.DataAccess;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CommunitiesMongoDbContext), typeof(CommunitiesMongoDbContextModel))]
