// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Channels;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class CommunityChannelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CommunityId>k__BackingField")]
        public static extern ref ulong CommunityId(CommunityChannel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(CommunityChannel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentId>k__BackingField")]
        public static extern ref ulong ParentId(CommunityChannel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Position>k__BackingField")]
        public static extern ref uint Position(CommunityChannel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref ChannelType Type(CommunityChannel @this);
    }
}
