// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Permissions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class EveryonePermissionsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Permissions>k__BackingField")]
        public static extern ref UserPermissions Permissions(EveryonePermissions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Priority>k__BackingField")]
        public static extern ref uint Priority(EveryonePermissions @this);
    }
}
