// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Channels;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class ForkChannelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MessageId>k__BackingField")]
        public static extern ref ulong MessageId(ForkChannel @this);
    }
}
