// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Invites;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class InviteUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref string Id(Invite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CommunityId>k__BackingField")]
        public static extern ref ulong CommunityId(Invite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(Invite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatorId>k__BackingField")]
        public static extern ref ulong CreatorId(Invite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
        public static extern ref DateTimeOffset? ExpiresAt(Invite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UsesCount>k__BackingField")]
        public static extern ref uint UsesCount(Invite @this);
    }
}
