// <auto-generated />
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Permissions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class OverwritePermissionsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Allow>k__BackingField")]
        public static extern ref UserPermissions Allow(OverwritePermissions @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Deny>k__BackingField")]
        public static extern ref UserPermissions Deny(OverwritePermissions @this);
    }
}
