// <auto-generated />
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Razdor.Communities.Domain.Channels;
using Razdor.Communities.Domain.Permissions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Razdor.Communities.Infrastructure.DataAccess
{
    public static class OverwritesPermissionChannelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_overwrites")]
        public static extern ref List<Overwrite> _overwrites(OverwritesPermissionChannel @this);
    }
}
